[window]
opacity = 0.7
padding = {x= 5, y= 5}

[font]
size = 12
normal = {family = "JetBrainsMonoNerdFont", style="Regular"}

[colors.primary]
foreground="#fbf1c7"
background="#1d2021"

[colors.normal]
black = "#282828"
red = "#cc241d"
green = "#98971a"
yellow = "#fabd2f"
blue = "#458588"
magenta = "#b16286"
cyan = "#83a598"
white = "#fbf1c7"

