#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           5
bspc config split_ratio          0.5

bspc config normal_border_color "#000000"
bspc config focused_border_color "#fbf1c7"
bspc config focus_follows_pointer true


./.config/bspwm/launch
